In [2]:
import numpy as np

In [3]:
# np.fliplr

In [4]:
m = 100
n = 15
t = np.linspace(0, 1, 100)
A = np.vander(t, n)
b = np.exp(np.sin(4*t))
b = b/2006.787453080206

In [5]:
x = np.linalg.inv(A.conj().T @ A) @ (A.conj().T @ b)

In [6]:
x[0]

-0.3648456670343876

In [7]:
np.linalg.pinv(A) @ b

array([ 1.00000005e+00, -8.38142302e+00,  3.06311713e+01, -6.41093758e+01,
        8.47288089e+01, -7.35408063e+01,  4.24466780e+01, -1.64170188e+01,
        4.38580605e+00, -8.18419691e-01,  7.43487527e-02, -6.23696655e-03,
        4.21287040e-03,  1.98998443e-03,  4.98315169e-04])

In [8]:
U, S, Vh = np.linalg.svd(A, full_matrices=False)
V = Vh.conj().T
S = np.diag(S)


In [9]:
x = V @ (np.linalg.inv(S) @ U.conj().T @ b)

In [10]:
x

array([ 1.00000005e+00, -8.38142302e+00,  3.06311713e+01, -6.41093758e+01,
        8.47288089e+01, -7.35408063e+01,  4.24466780e+01, -1.64170188e+01,
        4.38580605e+00, -8.18419691e-01,  7.43487527e-02, -6.23696655e-03,
        4.21287040e-03,  1.98998443e-03,  4.98315169e-04])

In [26]:
# Homework problem
U, S, Vh = np.linalg.svd(A)                             # Get the SVD of A
tol = np.max(A.shape) * S[0] * np.finfo(float).eps      #  
r = np.sum(S > tol)
S_inv = np.ones(r)/S
X = Vh.conj().T @ S_inv @ U[:, :r].conj().T


In [27]:
X

array([ 2.73167290e+07,  4.92965965e+07,  6.79347638e+07,  8.34577930e+07,
        9.60850328e+07,  1.06029079e+08,  1.13496197e+08,  1.18686694e+08,
        1.21795254e+08,  1.23011211e+08,  1.22518767e+08,  1.20497159e+08,
        1.17120758e+08,  1.12559104e+08,  1.06976881e+08,  1.00533827e+08,
        9.33845762e+07,  8.56784371e+07,  7.75591139e+07,  6.91643648e+07,
        6.06256057e+07,  5.20674640e+07,  4.36072869e+07,  3.53546114e+07,
        2.74106035e+07,  1.98674747e+07,  1.28078864e+07,  6.30435082e+06,
        4.18642018e+05, -4.79877267e+06, -9.30926693e+06, -1.30865422e+07,
       -1.61170524e+07, -1.84003526e+07, -1.99493555e+07, -2.07904823e+07,
       -2.09636908e+07, -2.05223675e+07, -1.95330677e+07, -1.80750912e+07,
       -1.62398784e+07, -1.41302164e+07, -1.18592445e+07, -9.54924831e+06,
       -7.33023783e+06, -5.33830333e+06, -3.71374754e+06, -2.59899517e+06,
       -2.13628406e+06, -2.46514631e+06, -3.71969142e+06, -6.02570859e+06,
       -9.49760950e+06, -

In [25]:
U[:, :r].shape

(100, 15)