In [1]:
import numpy as np

In [75]:
# Classical Gram-Schmidt algorithm
def cgs(A):
    """Classical gram schmidt computes the QR factorization of a matrix

    Args:
        x (arr): An m x n array of floats
    """
    # Set m and n
    m = A.shape[0]
    n = A.shape[1]
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v_j = A[:, j] # Set v_j = a_j; This initializes v_j when j = 0
        
        # This inner loop will not start executing until j-1 >= 2
        # This inner loop is designed to compute the off-diagonal entries of R
        # Note that we've used j in the range function instead of j-1 to account for Python's indexing
        for i in range(j):
            R[i, j] = Q[:, i] @ A[:, j] # Compute the off-diagonal entries of Q
            v_j = v_j - R[i, j]*Q[:, i]
        
        R[j, j] = np.linalg.norm(v_j) # Compute the jth diagonal entry of R
        
        Q[:, j] = v_j/R[j, j] # Compute the jth q, after the j-1 subtractions happen in the inner loop
                       # This initializes Q when j = 0
        
    return Q, R

In [76]:
A = np.array([[1, 2], [4, 5], [7, 8]])

In [77]:
cgs(A)

2
0 1
2
0 1


(array([[ 0.12309149,  0.90453403],
        [ 0.49236596,  0.30151134],
        [ 0.86164044, -0.30151134]]),
 array([[8.1240384 , 9.6011363 ],
        [0.        , 0.90453403]]))

In [78]:
np.linalg.qr(A)


(array([[-0.12309149,  0.90453403],
        [-0.49236596,  0.30151134],
        [-0.86164044, -0.30151134]]),
 array([[-8.1240384 , -9.6011363 ],
        [ 0.        ,  0.90453403]]))