In [2]:
import numpy as np

# Problem 23.1
Let $A$ be a nonsingular square matrix and let $A = QR$ and $A^*A = U^*U$ be $QR$ and Cholesky factorizations, respectively, with the usual normalizations $r_{jj}, u_{jj} > 0$. Is it true or false that $R = U$?

In [3]:
# Define a hermetian positive definite matrix A.
b = np.random.normal(size=(5, 5))
A = b @ b.T

In [4]:
# Check that A is hermetian
A == A.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [5]:
# Check that A is positive definite
np.linalg.eig(A)[0] > 0

array([ True,  True,  True,  True,  True])

In [6]:
# Compute the Cholesky factorization of A
U = np.linalg.cholesky(A)

In [7]:
# Compute the QR factorization of A
Q, R = np.linalg.qr(A)

In [8]:
# Check if the nonzero (i.e., upper diagonal) entries of R are the same as the entries of L transpose.
R == U.T

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True, False]])

It is not true that $R = U$, as is evidenced by the last computation.